# This is a Docker Compose configuration
# intended for development purposes only

version: "2"
services:
  bookstack_db:
    image: mysql:5.7.30
    container_name: bookstack_db
    environment:
        - PUID=1000
        - PGID=1000
        - MYSQL_ROOT_PASSWORD=icecream@2020
        - MYSQL_DATABASE=bookstack
        - MYSQL_USER=icecream
        - MYSQL_PASSWORD=icecream@2020
    volumes:
        - /home/data/bookstack/db:/var/lib/mysql
    ports:
      - 3307:3306
    restart: unless-stopped

  bookstack:
    image: bookstack:1.0.0
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=bookstack_db
      - DB_DATABASE=bookstack
      - DB_USERNAME=icecream
      - DB_PASSWORD=icecream@2020
      # Mail Setting
      - MAIL_DRIVER=smtp
      - MAIL_FROM=icecream@qq.com
      - MAIL_FROM_NAME="BookStack"
      # SMTP mail options
      - MAIL_HOST=smtp.exmail.qq.com
      - MAIL_PORT=465
      - MAIL_USERNAME=icecream@qq.com
      - MAIL_PASSWORD=icecream
      - MAIL_ENCRYPTION=ssl
      - APP_AUTO_LANG_PUBLIC=false
      # pdf渲染
      - WKHTMLTOPDF=/usr/bin/wkhtmltopdf
      # 存储为本地模式
      - STORAGE_TYPE=local
      # 默认语言为简体中文
      - APP_LANG=zh_CN
    volumes:
      - /home/data/bookstack/config:/config
    ports:
      - 8080:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
